name: Enforce pnpm Usage

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-package-manager:
    runs-on: ubuntu-latest
    name: Enforce pnpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for npm/yarn usage
        run: |
          # Check for npm or yarn commands in changed files
          git diff origin/master...HEAD --name-only | while read file; do
            if [ -f "$file" ]; then
              if grep -q "npm install\|npm run\|yarn add\|yarn install\|yarn run" "$file"; then
                echo "Error: Found npm or yarn commands in $file"
                echo "Please use pnpm instead:"
                echo "  npm install → pnpm install"
                echo "  npm run → pnpm run"
                echo "  npm add → pnpm add"
                echo "  yarn add → pnpm add"
                echo "  yarn install → pnpm install"
                echo "  yarn run → pnpm run"
                exit 1
              fi
            fi
          done

      - name: Check package.json packageManager field
        run: |
          if ! grep -q '"packageManager": "pnpm' package.json; then
            echo "Error: package.json must specify pnpm as packageManager"
            exit 1
          fi

      - name: Check for pnpm lockfile
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Error: pnpm-lock.yaml not found"
            exit 1
          fi

          if [ -f "package-lock.json" ] || [ -f "yarn.lock" ]; then
            echo "Error: Found npm or yarn lockfiles. Please remove them and use pnpm-lock.yaml only"
            exit 1
          fi
